# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!

target "pocket menu" do

pod 'MBProgressHUD', '~> 0.8'
pod 'SVProgressHUD'
pod 'PureLayout'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage','~> 3.7'
pod 'SZTextView'
pod 'IQKeyboardManager'
pod 'Parse'
pod 'RateView'
pod 'M13Checkbox'
pod 'MGSwipeTableCell'
pod 'CarbonKit', '~>2.1' 

end